global:
  domain: argocd.local

controllers:
  replicas: 1

server:
  replicas: 1
  service:
    type: LoadBalancer # Uses your MetalLB to give it an external IP
  extraArgs:
    - --insecure # Skip TLS for local lab (add cert later for prod)
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.local
