apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  type: ClusterIP # Or LoadBalancer if you want external access via MetalLB
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
